# action.yml
name: 'Docker Multistage'
description: 'Builds a multistage docker container into various tagged images'
inputs:
  dockerfile:
    description: 'The path to a multi-stage dockerfile'
    required: true
    default: 'Dockerfile'
  metadata:
    description: 'A metadata structure as output from https://github.com/docker/metadata-action'
    required: true
  platforms:
    description: 'A comma separated list of platform targets e.g. linux/amd64,linux/arm64'
    required: true
  stages:
    description: 'A comma separated list of stages to build'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-f"
    - ${{inputs.dockerfile}}
    - "--metadata"
    - ${{inputs.metadata}}
    - "--platforms"
    - ${{inputs.platforms}}
    - "--stages"
    - ${{inputs.stages}}
    - "-l"
    - "trace"
